name: ISU Machine Learning
url: http://chinmay.public.iastate.edu

exclude: [bibble, README.md, Makefile, screenshot.png]

# use this library to parse Markdown
markdown: redcarpet
redcarpet:
    extensions: [smart, tables, with_toc_data, strikethrough]

# colorize code snippets with the pygments module
highlighters: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
    - {key: faculty, name: Faculty}
#    - {key: staff, name: Staff}
#    - {key: postdoc, name: Researchers}
#    - {key: grad, name: Graduate Students}
#    - {key: collab, name: Collaborators}
    - {key: affiliate, name: Affiliates}

# Number of news stories on the front page.
front_page_news: 5

# Base pathname for links.
base: ''

collections:
  projects:
    output: true

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: People
      link: /people.html
    - title: Research
      link: /research/
    - title: Publications
      link: /publications.html
    - title: Code
      link: /code.html
